# Generated by Django 4.0.4 on 2023-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
