# Generated by Django 4.0.4 on 2023-12-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_user_telephone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOfFurnace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnace_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('serviceable', models.BooleanField(verbose_name='available to use')),
                ('max_temperature', models.PositiveIntegerField(verbose_name='max. temperature')),
                ('min_temperature', models.PositiveIntegerField(verbose_name='min. temperature')),
                ('is_clean', models.BooleanField(verbose_name='for clean materials')),
                ('user', models.ManyToManyField(related_name='furnaces', through='furnace_booking.BookingOfFurnace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingoffurnace',
            name='furnace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnace', to='furnace_booking.furnace'),
        ),
        migrations.AddField(
            model_name='bookingoffurnace',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bookingoffurnace',
            constraint=models.UniqueConstraint(fields=('date', 'furnace'), name='unique_booking_d_f'),
        ),
    ]
