# Generated by Django 4.0.4 on 2026-02-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnace_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnace',
            old_name='furnace_name',
            new_name='name',
        ),
    ]
