# Generated by Django 4.0.4 on 2026-02-05 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furnace_booking', '0002_rename_furnace_name_furnace_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnace',
            name='user',
        ),
        migrations.AddField(
            model_name='furnace',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('user', models.ManyToManyField(blank=True, related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingOfEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='furnace_booking.equipment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookingofequipment',
            constraint=models.UniqueConstraint(fields=('date', 'equipment'), name='unique_booking_d_e'),
        ),
    ]
