# Generated by Django 4.0.4 on 2026-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person'),
        ('furnace_booking', '0003_alter_furnace_user_equipment_bookingofequipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_users', to='users.person'),
        ),
        migrations.AlterField(
            model_name='furnace',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_users', to='users.person'),
        ),
    ]
