# Generated by Django 4.0.4 on 2026-02-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person'),
        ('furnace_booking', '0004_alter_equipment_user_alter_furnace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingofequipment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to='users.person'),
        ),
        migrations.AlterField(
            model_name='bookingoffurnace',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnace_bookings', to='users.person'),
        ),
    ]
