# Generated by Django 4.0.4 on 2026-03-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnace_booking', '0006_laboratory_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='furnace_booking.laboratory', verbose_name='laboratory'),
        ),
        migrations.AlterField(
            model_name='furnace',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='furnace_booking.laboratory', verbose_name='laboratory'),
        ),
    ]
